@url=http://localhost:8000/sql
@user=root
@pass=root

POST {{url}}
Accept: application/json
Authorization: Basic {{user}}:{{pass}}
Content-Type: application/text
Surreal-NS: test
Surreal-DB: test

DEFINE TABLE IF NOT EXISTS default;

###

POST {{url}}
Accept: application/json
Authorization: Basic {{user}}:{{pass}}
Content-Type: application/text
Surreal-NS: test
Surreal-DB: test

UPSERT default:hello CONTENT 
    {"key": "hello", "value": "world"};
UPSERT default:testing CONTENT 
    {"key": "testing", "value": "stuff"};

###

POST {{url}}
Accept: application/json
Authorization: Basic {{user}}:{{pass}}
Content-Type: application/text
Surreal-NS: test
Surreal-DB: test

SELECT key, value FROM test:hello;

###

POST {{url}}
Accept: application/json
Authorization: Basic {{user}}:{{pass}}
Content-Type: application/text
Surreal-NS: test
Surreal-DB: test

SELECT id, key, value FROM default;

###

POST {{url}}
Accept: application/json
Authorization: Basic {{user}}:{{pass}}
Content-Type: application/text
Surreal-NS: test
Surreal-DB: test

INFO FOR DB;

###

POST {{url}}
Accept: application/json
Authorization: Basic {{user}}:{{pass}}
Content-Type: application/text
Surreal-NS: test
Surreal-DB: test

REMOVE TABLE default;

